FROM node:20-slim

WORKDIR /app

COPY server/package*.json ./server/
RUN cd server && npm install

COPY server/tsconfig.json ./server/
COPY server/src ./server/src/
RUN cd server && npm run build

EXPOSE 5000

CMD ["node", "server/dist/index.js"]
